export default {
	"PUBNUB_SUBSCRIBE_KEY": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
	"PUBNUB_PUBLISH_KEY": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
	"GITHUB_CLIENT_ID": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
	"GITHUB_REDIRECT_URI": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
	"SERVER_URL": "http://localhost:3000",
	"USER_PRESENCE_CHANNEL" : "user_presence",
	"PRIVATE_CHANNEL_PRIFIX": "private6."
}
